PoemsGithub/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :poems

  
  get 'poems/(:id)/merge'=>'poems#update_merge', as: "poems_merge"
  post 'poems/(:id)/merge'=>'poems#merge'
  root to: "poems#index"

end

PoemsGithub/app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :poems
end

PoemsGithub/app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :users
  belongs_to :poems
end

PoemsGithub/app/models/poem.rb
class Poem < ActiveRecord::Base
  belongs_to :genre
  has_many :stars
end

PoemsGithub/app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :poem
end

PoemsGithub/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :owners
end

PoemsGithub/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

PoemsGithub/app/controllers/poems_controller.rb
class PoemsController < ApplicationController
require 'time'
# before_action :update_merge

  def new
    @is_edit = params[:is_edit].to_s
    @old_poem = Poem.where(:id => params[:poem_id], :is_active => true).first
    @poem = Poem.new
    @genres = Genre.where('id > 0')
  end

  def create
    @poem = Poem.new( {
      :title => params[:poem][:title],
      :content => params[:poem][:content],
      :genre_id => params[:poem][:genre_id],
      :user_id => params[:poem][:user_id],
      :owner_id => params[:poem][:owner_id],
      :is_wait => params[:poem][:is_wait],
      :is_active => params[:poem][:is_active],
      :is_selected => params[:poem][:is_selected]
    } )
    @poem.save
  end

  def index
    @poems = Poem.where(:is_active => true)
    @genres = Genre.pluck(:name,:id)
    if params[:genre_id] && params[:genre_id] != "-1"
      @poems = @poems.where(:genre_id => params[:genre_id])
    end
  end

  def show
    @poem = Poem.where(:id => params[:id]).first
    @poem_logs = Poem.where(:title => @poem.title)
    @user = User.where(:id => @poem.owner_id).first
    @commiter = User.where(:id => @poem.user_id).first
    @versions = @poem_logs.order("created_at desc").pluck(:created_at)
    if params[:poem]
      @poem = @poem_logs.where(:id => params[:poem][:id]).first
      @user = User.where(:id => @poem.owner_id).first
      @commiter = User.where(:id => @poem.user_id).first
    end
  end

  def merge
    @poem = Poem.where(:id => params[:id]).first
    @poem_logs = Poem.where(:title => @poem.title, :is_wait => true)
  end

  def update_merge
    poem = Poem.where(:id => params[:id]).first
    poem.is_selected = true
    poem.save
  #  redirect_to action: 'show', id: poem.id
    redirect_to("/poems/"+poem.id.to_s)
  end
end

PoemsGithub/app/helpers/application_helper.rb
module ApplicationHelper
end

PoemsGithub/app/helpers/home_helper.rb
module HomeHelper
end

PoemsGithub/app/helpers/poems_helper.rb
module PoemsHelper
end

PoemsGithub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoemsGithub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'プロフィール変更', edit_user_registration_path %> |
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "サインアップ", new_user_registration_path %> |
        <%= link_to "ログイン", new_user_session_path %>
      <% end %>
    </nav>
  </header>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<h1>PoemsGithub</h1>

<%= yield %>

</body>
</html>

PoemsGithub/app/views/poems/create.html.erb
<a href="/poems">一覧</a>
<p>作成しました</p>

PoemsGithub/app/views/poems/index.html.erb
<a href="/poems/new?is_edit=0">新規作成</a><br><br>

<%= form_tag('/', :method => :get) do %>
  <%= select_tag(:genre_id, options_for_select(@genres, :selected => params[:genre_id])) %>
  <%= submit_tag '絞り込む', {:name => nil } %>
<% end %>

<table>
  <thead>
    <tr>
      <td>ジャンル</td>
      <td>タイトル</td>
      <td>スター数</td>
      <td>コミット数</td>
    </tr>
  </thead>
  <tbody>
  <% @poems.each do |poem| %>
    <tr>
      <td><a href="?genre_id=<%= poem.genre.id %>"><%= poem.genre.name %></a></td>
      <td><a href="/poems/<%= poem.id %>"><%= poem.title %></a></td>
      <td><%= poem.stars.count %></td>
      <td><%= Poem.where(:title => poem.title).count %></td>
  <% end %>
  </tbody>
</table>

PoemsGithub/app/views/poems/merge.html.erb
<h1>Poem#merge</h1>

<% @poem_logs.each do |poem| %>
  <p>Title:<%= @poem.title %></p>
  <p>Content:<%= @poem.content %></p>
  <!--  <input type="button" onclick="location.href='/poems/<%= @poem.id %>/show/ %>'"value="merge"> -->
  <%= link_to "merge", poems_merge_path(@poem.id) %>
<% end %>

PoemsGithub/app/views/poems/new.html.erb
<h1>Poem#new</h1>
<%= form_for @poem do |f| %>
  <% if @is_edit == "0" %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :owner_id, :value => current_user.id %>
    <%= f.hidden_field :is_wait, :value => false %>
    <%= f.hidden_field :is_active, :value => true %>
    <%= f.hidden_field :is_selected, :value => false %>
    <p>title</p>
    <%= f.text_field :title %>
    <p>genre</p>
    <%= f.collection_select :genre_id, @genres, :id, :name %>
    <p>content</p>
    <%= f.text_field :content %>
  <% else %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :owner_id, :value => @old_poem.owner_id %>
    <%= f.hidden_field :is_wait, :value => true %>
    <%= f.hidden_field :is_active, :value => false %>
    <%= f.hidden_field :is_selected, :value => false %>
    <%= f.hidden_field :title, :value => @old_poem.title %>
    <%= f.hidden_field :genre_id, :value => @old_poem.genre_id %>
    <p>title</p>
    <%= @old_poem.title %>
    <p>genre</p>
    <%= @old_poem.genre.name %>
    <p>content</p>
    <%= f.text_field :content, :value => @old_poem.content %>
  <% end %>

  <p>
  <%= f.submit %>
  </p>
<% end %>

PoemsGithub/app/views/poems/show.html.erb
<h1>Poem#show</h1>

<%= form_tag('', :method => :get) do %>
  <%= collection_select(:poem, :id, @poem_logs, :id, :created_at) %>
  <%= submit_tag '表示', {:name => nil } %>
<% end %>

<p>タイトル:<%= @poem.title %></p>
<p>本文:<%= @poem.content %></p>
<p>オーナー:<%= @user.email %></p>
<p>編集者:<%= @commiter.email %></p>
<p>ジャンル:<%= @poem.genre.name %></p>

<% if @poem.is_active == true %>
  <input type="button" onclick="location.href='/poems/new?is_edit=1&poem_id=<%= @poem.id %>'"value="edit">
<% end %>

<p>
  <% if current_user.id == @poem.owner_id then %>
    <%= button_to "プルリクエストを見る", :action => "merge" %>
  <% end %>
</p>